### PR TITLE
Added new chapter for Continuations

### PR DESCRIPTION
**Pull request by amitdev**
Mostly a port of https://wiki.eclipse.org/Jetty/Feature/Continuations with broken link fixed and some minor corrections for Jetty 9.x.

### CODE REVIEW

**Comment by amitdev** [comment]
Any plans to pull this?

**Comment by amitdev** [comment]
@joakime, can you merge or review this?

**Comment by joakime** [comment]
We'll get the continuations groups here to look at it.

But why are you using Continuations with Jetty 9.x?

Servlet 3.1 and AsyncContext are the way you should be going.
In fact, there's been several dozen updates to AsyncContext handling in the past few months, and none to Continuations.  Continuations doesn't support Async I/O either.

**Comment by amitdev** [comment]
@joakime Thanks for the info. I was assuming Continuations was a nice way to make async handling which is compatible in previous version of Jetty as well. Looking at https://github.com/eclipse/jetty.project/blob/master/jetty-continuation/src/main/java/org/eclipse/jetty/continuation/Servlet3Continuation.java I assumed it should use AsyncContext if sevlet 3.1 is available. Is that not used anymore?

**Comment by amitdev** [comment]
@joakime Is this useful or not?

**Pull request merged**
